
CREATE TABLE businesses (
	business_id VARCHAR(50) PRIMARY KEY,
	name VARCHAR(200),
	address VARCHAR(200),
	city VARCHAR(200),
	state VARCHAR(100),
	postal_code VARCHAR(10),
	latitude float(8),
	longitude float(8),
	stars float(8),
	review_count INT,
	is_open INT,
	categories VARCHAR(700)
);
CREATE TABLE business_attributes (
	business_id VARCHAR(50) REFERENCES businesses,
	restaurants_table_service VARCHAR(200),
	wifi VARCHAR(200),
	bike_parking VARCHAR(200),
	business_parking VARCHAR(200),
	business_accepts_credit_cards VARCHAR(200),
	restaurants_reservations VARCHAR(200),
	wheelchair_accessible VARCHAR(200),
	caters VARCHAR(200),
	outdoor_seating VARCHAR(200),
	restaurants_good_for_groups VARCHAR(200),
	happy_hour VARCHAR(200),
	business_accepts_bitcoin VARCHAR(200),
	restaurants_price_range2 VARCHAR(200),
	ambience VARCHAR(200),
	has_tv VARCHAR(200),
	alcohol VARCHAR(200),
	good_for_meal VARCHAR(200),
	dogs_allowed VARCHAR(200),
	restaurants_take_out VARCHAR(200),
	noise_level VARCHAR(200),
	restaurants_attire VARCHAR(200),
	restaurants_delivery VARCHAR(200),
	good_for_kids VARCHAR(200),
	by_appointment_only VARCHAR(200),
	accepts_insurance VARCHAR(200),
	hair_specializes_in VARCHAR(200),
	good_for_dancing VARCHAR(200),
	best_nights VARCHAR(200),
	music VARCHAR(200),
	bYOB VARCHAR(200),
	coat_check VARCHAR(200),
	smoking VARCHAR(200),
	drive_thru VARCHAR(200),
	bYOB_corkage VARCHAR(200),
	corkage VARCHAR(200),
	restaurants_counter_service VARCHAR(200),
	ages_allowed VARCHAR(200),
	dietary_restrictions VARCHAR(200),
	open_24_hours VARCHAR(200)
);
CREATE TABLE users (
	user_id VARCHAR(50) PRIMARY KEY,
	name VARCHAR(50),
	review_count INT,
	yelping_since TIMESTAMP,
	useful INT,
	funny INT,
	cool INT,
	elite VARCHAR(80),
	friends VARCHAR(5000000),
	fans INT,
	average_stars float(8),
	compliment_hot INT,
	compliment_more INT,
	compliment_profile INT,
	compliment_cute INT,
	compliment_list INT,
	compliment_note INT,
	compliment_plain INT,
	compliment_cool INT,
	compliment_funny INT,
	compliment_writer INT,
	compliment_photos INT
);
CREATE TABLE reviews (
	review_id VARCHAR(50) PRIMARY KEY,
	user_id VARCHAR(50) REFERENCES users,
	business_id VARCHAR(50) REFERENCES businesses,
	stars INT,
	useful INT,
	funny INT,
	cool INT,
	text VARCHAR(6000),
	date TIMESTAMP
);



